import { defer } from 'lodash'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Platzi',
  description: 'Generated by platzi',
}

export const script = {
  defer: true,
  'data-domain': 'yourdomain.com',
  src: 'https://plausible.io/js/script.js',
} 


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
